<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kelvin Wong">
<meta name="dcterms.date" content="2026-05-26">
<meta name="description" content="A deliberately small two-maturity, five-day example used to walk through the mechanics of PCA on yield changes: centering, the covariance matrix, eigendecomposition, the geometric meaning of the rotation, the PC scores, and the reverse construction of stress scenarios.">

<title>PCA on Yield Curves: a simple example – WONG | Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-6b6957c917596b414ec0b78690761e87.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-4ea889f8855cf48074658e9f0fd2e67a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark-e70ec2cf6ff0e462ed6772ad11d06af6.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../../site_libs/bootstrap/bootstrap-4ea889f8855cf48074658e9f0fd2e67a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<meta name="google-site-verification" content="haUJj-wPPgU5a0qyePIluTiO4UIAxMqEWfWtq-IIPjA">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">WONG | Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kelvin1189"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../../index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS feed">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#the-raw-data" id="toc-the-raw-data" class="nav-link active" data-scroll-target="#the-raw-data">The raw data</a></li>
  <li><a href="#the-data-is-highly-correlated" id="toc-the-data-is-highly-correlated" class="nav-link" data-scroll-target="#the-data-is-highly-correlated">The data is highly correlated</a></li>
  <li><a href="#extracting-the-principal-components" id="toc-extracting-the-principal-components" class="nav-link" data-scroll-target="#extracting-the-principal-components">Extracting the principal components</a></li>
  <li><a href="#pca-as-a-rotation" id="toc-pca-as-a-rotation" class="nav-link" data-scroll-target="#pca-as-a-rotation">PCA as a rotation</a></li>
  <li><a href="#the-pca-scores" id="toc-the-pca-scores" class="nav-link" data-scroll-target="#the-pca-scores">The PCA scores</a></li>
  <li><a href="#sec-caveat" id="toc-sec-caveat" class="nav-link" data-scroll-target="#sec-caveat">2D limitations</a></li>
  <li><a href="#reverse-construction-building-stress-scenarios" id="toc-reverse-construction-building-stress-scenarios" class="nav-link" data-scroll-target="#reverse-construction-building-stress-scenarios">Reverse construction: building stress scenarios</a></li>
  <li><a href="#what-carries-to-the-real-data-setting" id="toc-what-carries-to-the-real-data-setting" class="nav-link" data-scroll-target="#what-carries-to-the-real-data-setting">What carries to the real-data setting</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading">Further reading</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PCA on Yield Curves: a simple example</h1>
  <div class="quarto-categories">
    <div class="quarto-category">PCA</div>
    <div class="quarto-category">yield-curves</div>
    <div class="quarto-category">fixed-income</div>
    <div class="quarto-category">risk-management</div>
  </div>
  </div>

<div>
  <div class="description">
    A deliberately small two-maturity, five-day example used to walk through the mechanics of PCA on yield changes: centering, the covariance matrix, eigendecomposition, the geometric meaning of the rotation, the PC scores, and the reverse construction of stress scenarios.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kelvin Wong </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 26, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Principal component analysis is one of the standard tools used to decompose yield curve movements into a small number of independent factors. On real yield curve data with ten or more tenors, the procedure typically delivers a Level / Slope / Curvature decomposition that accounts for roughly 95% of variance. The mechanism is described in many places; the canonical reference is <span class="citation" data-cites="litterman1991">Litterman and Scheinkman (<a href="#ref-litterman1991" role="doc-biblioref">1991</a>)</span>.</p>
<p>This article does not work on a real yield curve. It works on a deliberately small example — two tenors, five days, fabricated numbers chosen so that every value is reproducible by hand. The point is to fix the mechanics of the method in a setting where every intermediate quantity can be drawn on a single page. With two tenors, the data lives in the plane; the rotation that PCA performs is a literal rotation, and the eigenvectors are literal axes.</p>
<p>A two-tenor, five-day example has real limitations, and the limitations matter for what readers should and should not take away. They are stated explicitly in <a href="#sec-caveat">§ 2D limitations</a> below before the stress-scenario construction. The mechanism shown here extends without modification to ten or sixty tenors; the <em>interpretation</em> of components beyond the first is what changes when more tenors are available.</p>
<section id="the-raw-data" class="level2">
<h2 class="anchored" data-anchor-id="the-raw-data">The raw data</h2>
<p>The example uses five days of observed daily changes (in basis points) on two hypothetical tenors, a “2-year” and a “10-year”:</p>
<div id="tbl-raw" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-raw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Five days of yield changes (fabricated data).
</figcaption>
<div aria-describedby="tbl-raw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Day</th>
<th>Δy₂ (bps)</th>
<th>Δy₁₀ (bps)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Day 1</td>
<td>2.0</td>
<td>1.5</td>
</tr>
<tr class="even">
<td>Day 2</td>
<td>5.0</td>
<td>4.0</td>
</tr>
<tr class="odd">
<td>Day 3</td>
<td>−3.0</td>
<td>−2.0</td>
</tr>
<tr class="even">
<td>Day 4</td>
<td>−1.0</td>
<td>−1.0</td>
</tr>
<tr class="odd">
<td>Day 5</td>
<td>1.0</td>
<td>0.5</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The sample means are 0.80 bps on the 2-year and 0.60 bps on the 10-year. PCA operates on deviations from the mean, so the first step is to subtract these:</p>
<div id="tbl-centered" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-centered-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Mean-centered yield changes. Each column sums to zero.
</figcaption>
<div aria-describedby="tbl-centered-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Day</th>
<th>Centered Δy₂</th>
<th>Centered Δy₁₀</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Day 1</td>
<td>1.2</td>
<td>0.9</td>
</tr>
<tr class="even">
<td>Day 2</td>
<td>4.2</td>
<td>3.4</td>
</tr>
<tr class="odd">
<td>Day 3</td>
<td>−3.8</td>
<td>−2.6</td>
</tr>
<tr class="even">
<td>Day 4</td>
<td>−1.8</td>
<td>−1.6</td>
</tr>
<tr class="odd">
<td>Day 5</td>
<td>0.2</td>
<td>−0.1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Centering matters because variance is measured relative to the mean. PCA finds the directions of maximum variance; if the data is not centered, the first principal component will point partly toward wherever the mean happens to sit rather than toward the direction of greatest variability.</p>
</section>
<section id="the-data-is-highly-correlated" class="level2">
<h2 class="anchored" data-anchor-id="the-data-is-highly-correlated">The data is highly correlated</h2>
<p>Plotting the centered data on a scatter shows the central problem PCA is built to address. The five points lie nearly on a straight line: a day with a large move in the 2-year is almost always a day with a large move in the same direction in the 10-year. The sample correlation is approximately 0.99.</p>
<div id="fig-before-pca" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Scatter plot of centered 2-year vs 10-year daily yield changes showing near-perfect linear relationship">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-before-pca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="before_pca.png" class="img-fluid figure-img" alt="Scatter plot of centered 2-year vs 10-year daily yield changes showing near-perfect linear relationship">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-before-pca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Centered daily changes on the two tenors. The five points lie on a near-45° line, indicating very high correlation. Shocking the 2-year and 10-year independently in this sample would generate scenarios that have never been observed.
</figcaption>
</figure>
</div>
<p>This is the condition that makes independent stress testing on the original variables unrealistic. A scenario like “+5 bps to the 2-year, 0 to the 10-year” lies far off the cloud of observed joint behaviour and would imply a yield curve geometry the sample never produced. PCA addresses this by finding new axes — rotated relative to the original ones — along which the data is uncorrelated by construction.</p>
</section>
<section id="extracting-the-principal-components" class="level2">
<h2 class="anchored" data-anchor-id="extracting-the-principal-components">Extracting the principal components</h2>
<p>The sample covariance matrix (using the n − 1 = 4 denominator, matching R’s <code>cov()</code> and <code>prcomp()</code> defaults) is:</p>
<p><span class="math display">\[
\Sigma = \begin{bmatrix} 9.20 &amp; 7.025 \\ 7.025 &amp; 5.425 \end{bmatrix}
\]</span></p>
<p>Solving the characteristic equation det(Σ − λI) = 0 gives two eigenvalues and two corresponding eigenvectors:</p>
<div id="tbl-eig" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-eig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Eigendecomposition of the sample covariance matrix.
</figcaption>
<div aria-describedby="tbl-eig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Component</th>
<th>Eigenvalue</th>
<th>Eigenvector</th>
<th>Variance share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PC1</td>
<td>14.587</td>
<td>[0.7936, 0.6085]</td>
<td>99.74%</td>
</tr>
<tr class="even">
<td>PC2</td>
<td>0.038</td>
<td>[−0.6085, 0.7936]</td>
<td>0.26%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>PC1 points in the direction (0.79, 0.61) — roughly along the 45° line where the 2-year and 10-year move together. This is naturally interpreted as the <strong>Level</strong> factor: a positive PC1 score corresponds to both yields moving up together.</p>
<p>PC2 points in the direction (−0.61, 0.79), perpendicular to PC1. The 2-year and 10-year move in opposite directions along it. With only two tenors, this can be informally read as <strong>Steepness</strong>, with the caveat covered in <a href="#sec-caveat">§ 2D limitations</a>.</p>
<p>The 99.74% / 0.26% split is an artefact of this toy. The two tenors here are nearly collinear in this 5-day sample, so almost all variance is captured by the first component. On real yield curves with ten or more tenors, PC1 typically explains 70–90% of variance, PC2 a further 5–15%, and PC3 around 1–5%. Reporting “PC1 explains 99.7%” as a general fact about yield curves would be misleading; it is a fact about this toy.</p>
<p>Two conventions affect reproducibility. Eigenvectors are defined up to sign, so software may return (−0.79, −0.61) instead of (0.79, 0.61); the two are the same direction and the choice does not change any downstream analysis. The convention adopted here is that PC1’s first loading is positive. The covariance estimator uses the n − 1 denominator throughout, matching R’s defaults; <code>numpy.cov</code> requires <code>ddof=1</code> to match.</p>
</section>
<section id="pca-as-a-rotation" class="level2">
<h2 class="anchored" data-anchor-id="pca-as-a-rotation">PCA as a rotation</h2>
<p>The eigendecomposition above is correct but somewhat abstract. There is a more concrete geometric reading: <strong>PCA is the rotation of the data that maximises the variance along one axis.</strong> Starting from the raw centered data and rotating progressively, the variance along the horizontal axis grows until it reaches a maximum at one specific angle. That angle is the angle of PC1; the maximum value is the PC1 eigenvalue.</p>
<div id="fig-rotation-sequence" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Six-panel figure showing the centered data rotated by 0, 7.5, 15, 22.5, 30, and 37.5 degrees, with variance along the horizontal axis growing from 9.20 to 14.59">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rotation-sequence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="rotation_sequence.png" class="img-fluid figure-img" alt="Six-panel figure showing the centered data rotated by 0, 7.5, 15, 22.5, 30, and 37.5 degrees, with variance along the horizontal axis growing from 9.20 to 14.59">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rotation-sequence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: PCA as a rotation. Six panels show the same five centered points after rotating by progressively larger angles, from 0° (raw data) to 37.5° (full PC1 alignment). Above each panel: the rotation angle and the variance along the horizontal axis. The variance grows from 9.20 (the variance of the raw Δy₂) to 14.59 (the PC1 eigenvalue) as the rotation approaches the PC1 angle. The final frame is identical to the PC1 / PC2 scores plot shown in the next section.
</figcaption>
</figure>
</div>
<p>The angle of PC1 from the original 2-year axis is arctan(0.6085 / 0.7936) ≈ 37.48°. Rotating by exactly this angle aligns the long spine of the data cloud with the horizontal axis, leaving only the small residual spread perpendicular to it. The terminal variance of 14.59 in the right-most panel is exactly the PC1 eigenvalue: the eigenvalue <em>is</em> the variance along the principal direction.</p>
<p>The same process can be shown as an animation. The data rotates continuously while a tracking dot moves along the variance-vs-angle curve on the right; the dot reaches its peak at 37.48° and falls back as the rotation continues past the optimum.</p>
<div id="fig-rotation-animation" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Animated GIF showing yield change data rotating continuously while variance along the horizontal axis traces out a curve with a maximum at the PC1 angle">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rotation-animation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="rotation_animation.gif" class="img-fluid figure-img" alt="Animated GIF showing yield change data rotating continuously while variance along the horizontal axis traces out a curve with a maximum at the PC1 angle">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rotation-animation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Animated rotation. The left panel shows the data rotating; the right panel shows the variance along the horizontal axis as a function of rotation angle. The maximum is reached at 37.48° and equals the PC1 eigenvalue.
</figcaption>
</figure>
</div>
<p>The visualisation uses one shortcut for readability: the data points are shown rotating while the page-frame stays fixed. The mathematically clean statement is the reverse — the data stays fixed and the <em>axes</em> rotate to align with it. The two views are equivalent.</p>
</section>
<section id="the-pca-scores" class="level2">
<h2 class="anchored" data-anchor-id="the-pca-scores">The PCA scores</h2>
<p>Projecting each day’s centered observation onto the two eigenvectors gives the <strong>PCA scores</strong>: the coordinates of each day in the new, rotated coordinate system.</p>
<div id="tbl-scores" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-scores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: PCA scores. Each row is one day’s coordinates in the (PC1, PC2) system.
</figcaption>
<div aria-describedby="tbl-scores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Day</th>
<th>PC1 (Level)</th>
<th>PC2 (Steepness)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Day 1</td>
<td>1.500</td>
<td>−0.020</td>
</tr>
<tr class="even">
<td>Day 2</td>
<td>5.402</td>
<td>0.143</td>
</tr>
<tr class="odd">
<td>Day 3</td>
<td>−4.598</td>
<td>0.249</td>
</tr>
<tr class="even">
<td>Day 4</td>
<td>−2.402</td>
<td>−0.174</td>
</tr>
<tr class="odd">
<td>Day 5</td>
<td>0.098</td>
<td>−0.198</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The PC1 column ranges from −4.60 to +5.40 — about ten basis points of spread. The PC2 column ranges from −0.20 to +0.25 — about half a basis point of spread. This twenty-fold scale difference is the 99.74%-vs-0.26% variance split rendered in the data.</p>
<p>A direct verification of one row: for Day 1, PC1 = 1.2 × 0.7936 + 0.9 × 0.6085 = 1.500, and PC2 = 1.2 × (−0.6085) + 0.9 × 0.7936 = −0.020.</p>
<p>The before-and-after scatter makes the rotation visible in a single image. Side by side, the correlated raw data and the uncorrelated scores are easy to compare:</p>
<div id="fig-before-after" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Side-by-side comparison: left panel shows correlated raw data, right panel shows uncorrelated PCA scores">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-before-after-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="before_after_pca.png" class="img-fluid figure-img" alt="Side-by-side comparison: left panel shows correlated raw data, right panel shows uncorrelated PCA scores">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-before-after-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Before and after PCA. <strong>Left:</strong> raw centered changes lie on a near-45° line, indicating high correlation. <strong>Right:</strong> after projection onto the principal components, the data spreads almost entirely along PC1 with negligible spread on PC2. The dramatic asymmetry between the axis scales — ±5 on the horizontal vs ±0.3 on the vertical — is the visual encoding of the 99.74% / 0.26% variance split.
</figcaption>
</figure>
</div>
<p>Day 5 is worth a sentence on its own. Its raw change was (+1.0, +0.5) bps — both yields rose. But that change was very close to the average daily move in the sample, (+0.8, +0.6). So in the <em>centered</em> frame, Day 5 shows almost no level movement. What residual movement remained was a slight twist: the 2-year rose marginally more than its average while the 10-year rose marginally less. PC2 captures exactly that. Inspection of the raw yields would not have flagged Day 5 as a structurally unusual day; the PC2 column does.</p>
</section>
<section id="sec-caveat" class="level2">
<h2 class="anchored" data-anchor-id="sec-caveat">2D limitations</h2>
<p>Two facts about this toy example need explicit statement before any of the apparatus is interpreted too literally.</p>
<p>First, PCA on two variables can only ever produce two components. The famous Level / Slope / Curvature decomposition of <span class="citation" data-cites="litterman1991">Litterman and Scheinkman (<a href="#ref-litterman1991" role="doc-biblioref">1991</a>)</span> requires at least three maturities to surface. Curvature is structurally absent from this article. The label “Steepness” applied to PC2 here is a useful intuition pump — a 2-vs-10 spread is genuinely related to the slope of a yield curve — but it is not the same object as the second principal component that emerges from a full multi-maturity decomposition. On a real ten-tenor dataset, PC2 exhibits a sign pattern that is clearly identifiable as slope (short tenors load with one sign, long tenors with the other), and PC3 exhibits the characteristic curvature pattern (the middle tenors loading opposite to the ends). None of that can be demonstrated here.</p>
<p>Second, this article works on yield <em>changes</em>, not yield <em>levels</em>. The distinction matters. Levels are highly persistent: PC1 of yield levels tends to capture “where on average yields are sitting” rather than “how they move.” Stress testing requires the second concept. The Litterman–Scheinkman decomposition, and virtually all regulatory frameworks built on it, operate on changes.</p>
</section>
<section id="reverse-construction-building-stress-scenarios" class="level2">
<h2 class="anchored" data-anchor-id="reverse-construction-building-stress-scenarios">Reverse construction: building stress scenarios</h2>
<p>The forward use of PCA goes from raw yield changes to PCA scores. The reverse use goes from a hypothetical PC score back to a yield change, by projecting the score along the eigenvector and adding the sample mean:</p>
<p><span class="math display">\[
\text{Stressed change} = \text{Mean} + (\text{Shock magnitude}) \times \text{Eigenvector}
\]</span></p>
<p>In risk frameworks the shock magnitude is calibrated in standard deviations of the relevant principal component. The standard deviations are the square roots of the eigenvalues:</p>
<ul>
<li>1 SD of PC1 = √14.587 ≈ 3.819 bps</li>
<li>1 SD of PC2 = √0.038 ≈ 0.196 bps</li>
</ul>
<p>PC1’s standard deviation is roughly nineteen times PC2’s. This is not an external choice; it is a property of the data, telling the modeller automatically that level shifts are much larger than pure twists historically.</p>
<p>The “1 SD” choice here is for illustration. Real regulatory frameworks use higher percentiles — Solvency II uses 99.5% one-year Value-at-Risk, which corresponds to roughly 2.58 standard deviations under a Gaussian assumption. The mechanism is identical; only the multiplier changes.</p>
<section id="scenario-a-a-level-shock-1-sd-on-pc1" class="level3">
<h3 class="anchored" data-anchor-id="scenario-a-a-level-shock-1-sd-on-pc1">Scenario A: a level shock (+1 SD on PC1)</h3>
<p>Shocking PC1 by +1 SD (3.819) and holding PC2 at zero simulates a coherent upward shift of the curve that respects the historical correlation between the 2-year and 10-year.</p>
<div id="tbl-scenario-a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-scenario-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Scenario A: +1 SD shock on PC1.
</figcaption>
<div aria-describedby="tbl-scenario-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 24%">
<col style="width: 33%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th>Tenor</th>
<th>Mean change (bps)</th>
<th>PC1 impact (bps)</th>
<th>Stressed change (bps)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2-Year</td>
<td>0.80</td>
<td>3.819 × 0.7936 = 3.031</td>
<td>3.831</td>
</tr>
<tr class="even">
<td>10-Year</td>
<td>0.60</td>
<td>3.819 × 0.6085 = 2.324</td>
<td>2.924</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Both yields rise, in approximately the historical ratio of co-movement. This is a statistically coherent “parallel up” scenario — one that the joint distribution of the historical sample would not consider improbable on geometric grounds.</p>
</section>
<section id="scenario-b-a-steepness-shock-1-sd-on-pc2" class="level3">
<h3 class="anchored" data-anchor-id="scenario-b-a-steepness-shock-1-sd-on-pc2">Scenario B: a steepness shock (+1 SD on PC2)</h3>
<p>Shocking PC2 by +1 SD (0.196) and holding PC1 at zero isolates a pure curve twist.</p>
<div id="tbl-scenario-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-scenario-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Scenario B: +1 SD shock on PC2.
</figcaption>
<div aria-describedby="tbl-scenario-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 23%">
<col style="width: 36%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Tenor</th>
<th>Mean change (bps)</th>
<th>PC2 impact (bps)</th>
<th>Stressed change (bps)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2-Year</td>
<td>0.80</td>
<td>0.196 × (−0.6085) = −0.119</td>
<td>0.681</td>
</tr>
<tr class="even">
<td>10-Year</td>
<td>0.60</td>
<td>0.196 × 0.7936 = 0.155</td>
<td>0.755</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The 2-year rises slightly less than its mean while the 10-year rises slightly more. The 10-vs-2 spread widens by roughly 0.27 bps relative to the unstressed baseline — a mild steepening.</p>
<p>The asymmetry between Scenario A and Scenario B is the point of the exercise. A “1 SD” shock to Level produces about 3 bps of yield movement; the same “1 SD” shock to Steepness produces about 0.15 bps. The framework recognises — without being told — that level shifts are historically large and pure twists are historically small. This is the role of the eigenvalues: they convert the abstract idea of a “one-standard-deviation shock” into the right scale for each factor.</p>
</section>
</section>
<section id="what-carries-to-the-real-data-setting" class="level2">
<h2 class="anchored" data-anchor-id="what-carries-to-the-real-data-setting">What carries to the real-data setting</h2>
<p>Three observations from this toy carry directly into PCA on real, multi-tenor yield curve datasets.</p>
<ul>
<li>PCA finds independent factors from correlated data by rotating the coordinate system. The mechanism is identical at any dimensionality; what changes is how many components are needed to capture most of the variance.</li>
<li>The eigenvalues are not just diagnostic numbers; they automatically provide the scale at which each factor can be plausibly shocked. This is what makes PCA useful for stress generation, not only descriptive analysis.</li>
<li>The interpretation of PC1 as Level survives the move from two tenors to ten or more. The interpretation of PC2 as Slope and PC3 as Curvature requires the full multi-tenor dataset to demonstrate; the 2D toy cannot show it.</li>
</ul>
</section>
<section id="further-reading" class="level2">
<h2 class="anchored" data-anchor-id="further-reading">Further reading</h2>
<p><span class="citation" data-cites="litterman1991">Litterman and Scheinkman (<a href="#ref-litterman1991" role="doc-biblioref">1991</a>)</span> is the seminal paper introducing PCA to fixed-income portfolios and identifying the Level / Slope / Curvature decomposition. <span class="citation" data-cites="hull2018risk">Hull (<a href="#ref-hull2018risk" role="doc-biblioref">2018</a>)</span> covers Value at Risk and historical simulation, including step-by-step numerical examples of the covariance-to-eigenvalue-to-stress-scenario workflow used here. <span class="citation" data-cites="tuckman2022fixed">Tuckman and Serrat (<a href="#ref-tuckman2022fixed" role="doc-biblioref">2022</a>)</span> has chapters on empirical risk metrics that show how asset-liability management desks use PCA to measure portfolio sensitivity to twists and butterfly shifts. <span class="citation" data-cites="alexander2008market">Alexander (<a href="#ref-alexander2008market" role="doc-biblioref">2008</a>)</span> gives the explicit matrix-algebra implementation of PCA in finance.</p>
<hr>
<p><em>Source code for the figures in this article is available <a href="https://github.com/kelvin1189/actuarial-modeling-notes/tree/main/posts/pca-toy/code">in the repo</a>.</em></p>
<p>Comments and corrections welcome.</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-alexander2008market" class="csl-entry" role="listitem">
Alexander, Carol. 2008. <em>Market Risk Analysis, Volume II: Practical Financial Econometrics</em>. Wiley.
</div>
<div id="ref-hull2018risk" class="csl-entry" role="listitem">
Hull, John C. 2018. <em>Risk Management and Financial Institutions</em>. 5th ed. Wiley.
</div>
<div id="ref-litterman1991" class="csl-entry" role="listitem">
Litterman, Robert, and Jose Scheinkman. 1991. <span>“Common Factors Affecting Bond Returns.”</span> <em>Journal of Fixed Income</em> 1 (1): 54–61. <a href="https://doi.org/10.3905/jfi.1991.692347">https://doi.org/10.3905/jfi.1991.692347</a>.
</div>
<div id="ref-tuckman2022fixed" class="csl-entry" role="listitem">
Tuckman, Bruce, and Angel Serrat. 2022. <em>Fixed Income Securities: Tools for Today’s Markets</em>. 4th ed. Wiley.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/kelvin1189\.github\.io\/actuarial-modeling-notes\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<script src="https://utteranc.es/client.js" repo="kelvin1189/actuarial-modeling-notes" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><em>Disclaimer.</em> The content on this website is for educational and informational purposes only and does not constitute financial, investment, legal, or professional actuarial advice. The views expressed here are my own and do not reflect the position of any current or past employer. All code and models are provided “as is” without warranty.</p>
<p><span class="footer-meta">© 2026 Kelvin Wong · Source on <a href="https://github.com/kelvin1189/actuarial-modeling-notes">GitHub</a> · Built with <a href="https://quarto.org">Quarto</a></span></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>