<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kelvin Wong">
<meta name="dcterms.date" content="2026-05-30">
<meta name="description" content="A 10-week, 3-tenor (2y/5y/10y) worked example that extends the earlier 2-tenor PCA toy into the three dimensions needed to demonstrate the canonical Level / Slope / Curvature decomposition.">

<title>PCA on Yield Curves: a 10-week, 3-tenor example – WONG | Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-6b6957c917596b414ec0b78690761e87.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-4ea889f8855cf48074658e9f0fd2e67a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark-e70ec2cf6ff0e462ed6772ad11d06af6.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../../site_libs/bootstrap/bootstrap-4ea889f8855cf48074658e9f0fd2e67a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-ZE7XDNH3W9"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-ZE7XDNH3W9', { 'anonymize_ip': true});
</script>
<style>html{ scroll-behavior: smooth; }</style>
<meta name="google-site-verification" content="haUJj-wPPgU5a0qyePIluTiO4UIAxMqEWfWtq-IIPjA">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">WONG | Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kelvin1189"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../../index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS feed">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#the-raw-data" id="toc-the-raw-data" class="nav-link active" data-scroll-target="#the-raw-data">The raw data</a></li>
  <li><a href="#the-data-is-highly-correlated" id="toc-the-data-is-highly-correlated" class="nav-link" data-scroll-target="#the-data-is-highly-correlated">The data is highly correlated</a></li>
  <li><a href="#extracting-the-principal-components" id="toc-extracting-the-principal-components" class="nav-link" data-scroll-target="#extracting-the-principal-components">Extracting the principal components</a></li>
  <li><a href="#before-and-after-pca" id="toc-before-and-after-pca" class="nav-link" data-scroll-target="#before-and-after-pca">Before and after PCA</a></li>
  <li><a href="#pca-as-variance-aligned-axes" id="toc-pca-as-variance-aligned-axes" class="nav-link" data-scroll-target="#pca-as-variance-aligned-axes">PCA as variance-aligned axes</a></li>
  <li><a href="#the-pca-scores" id="toc-the-pca-scores" class="nav-link" data-scroll-target="#the-pca-scores">The PCA scores</a></li>
  <li><a href="#reverse-construction-building-stress-scenarios" id="toc-reverse-construction-building-stress-scenarios" class="nav-link" data-scroll-target="#reverse-construction-building-stress-scenarios">Reverse construction: building stress scenarios</a></li>
  <li><a href="#sec-limits" id="toc-sec-limits" class="nav-link" data-scroll-target="#sec-limits">Limitations of this example</a></li>
  <li><a href="#stresses-as-yield-curve-transformations" id="toc-stresses-as-yield-curve-transformations" class="nav-link" data-scroll-target="#stresses-as-yield-curve-transformations">Stresses as yield-curve transformations</a></li>
  <li><a href="#sec-var" id="toc-sec-var" class="nav-link" data-scroll-target="#sec-var">A 99.5% VaR stress example</a></li>
  <li><a href="#what-changes-when-going-from-2-tenors-to-many-tenors" id="toc-what-changes-when-going-from-2-tenors-to-many-tenors" class="nav-link" data-scroll-target="#what-changes-when-going-from-2-tenors-to-many-tenors">What changes when going from 2 tenors to many tenors</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PCA on Yield Curves: a 10-week, 3-tenor example</h1>
<p class="subtitle lead">Article 2</p>
  <div class="quarto-categories">
    <div class="quarto-category">series</div>
    <div class="quarto-category">PCA</div>
    <div class="quarto-category">yield-curves</div>
    <div class="quarto-category">stress-scenarios</div>
    <div class="quarto-category">risk-management</div>
  </div>
  </div>

<div>
  <div class="description">
    A 10-week, 3-tenor (2y/5y/10y) worked example that extends the earlier 2-tenor PCA toy into the three dimensions needed to demonstrate the canonical Level / Slope / Curvature decomposition.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kelvin Wong </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 30, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>This is the second article of a two-article series on PCA for yield curves. The series introduction (covering the stress-testing problem PCA addresses, the eigenvalue derivation, and why the procedure maximises variance) is in <a href="../00-intro/index.qmd">Article 0</a>. The previous article, <a href="../01-2tenor-toy/index.qmd">Article 1</a>, worked through PCA on a deliberately small 2-tenor, 5-day example where the rotation could be drawn explicitly. This article extends the machinery to three tenors, where the canonical three-factor Level / Slope / Curvature decomposition first appears.</p>
</div>
</div>
</div>
<p><a href="../01-2tenor-toy/index.qmd">Article 1</a> walked through PCA on two tenors and five days. That example was small enough that every number could be checked by hand and the rotation could be drawn on a single page. It had one structural limit: with only two original variables, PCA can only produce two principal components, and the second is forced by orthogonality to be perpendicular to the first. The famous three-factor Level / Slope / Curvature decomposition of <span class="citation" data-cites="litterman1991">Litterman and Scheinkman (<a href="#ref-litterman1991" role="doc-biblioref">1991</a>)</span> was therefore impossible to demonstrate. <a href="../01-2tenor-toy/index.qmd">Article 1</a> stated this honestly and stopped.</p>
<p>This article fills that gap. The dataset is 10 weeks of changes (in basis points) on three tenors — a “2y”, a “5y”, and a “10y” — chosen to produce a clean three-factor structure with variance shares close to the textbook 85% / 12% / 3%. Everything else is the same as before: forward decomposition via the covariance matrix, scores as projections onto eigenvectors, reverse construction of stress scenarios by adding shock vectors back to the mean. The mathematical foundation for what the procedure is doing — the Lagrangian derivation, the eigenvalue equation, the spectral theorem — is in <a href="../00-intro/index.qmd">Article 0</a> and not repeated here.</p>
<p>A note on the data, made explicit because it matters: the 10 weeks below are hand-engineered to make the L/S/C decomposition come out crisply for pedagogical reasons. The eigenvector sign patterns and variance shares are not noisy. On real yield curve data the same patterns appear but with more measurement noise and occasional cross-loadings; the structure I am showing is what practitioners <em>expect</em> to see in long samples, not what they always see in any individual 10-week window. PCA on real Taiwan TWD data — with the noise, cross-loadings, and comparison to Nelson-Siegel basis functions that a serious application requires — is the subject of <a href="../../ics-dns-twd-yc/03-pca-twd/index.qmd">Article 3 of the DNS series</a> (forthcoming).</p>
<section id="the-raw-data" class="level2">
<h2 class="anchored" data-anchor-id="the-raw-data">The raw data</h2>
<p>The 10 weekly changes:</p>
<div id="tbl-raw" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-raw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: 10 weekly yield changes on (2y, 5y, 10y), in basis points.
</figcaption>
<div aria-describedby="tbl-raw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Week</th>
<th>Δy(2y) (bps)</th>
<th>Δy(5y) (bps)</th>
<th>Δy(10y) (bps)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>W1</td>
<td>+5</td>
<td>+5</td>
<td>+5</td>
</tr>
<tr class="even">
<td>W2</td>
<td>−4</td>
<td>−4</td>
<td>−4</td>
</tr>
<tr class="odd">
<td>W3</td>
<td>+6</td>
<td>+5</td>
<td>+4</td>
</tr>
<tr class="even">
<td>W4</td>
<td>−5</td>
<td>−4</td>
<td>−3</td>
</tr>
<tr class="odd">
<td>W5</td>
<td>+3</td>
<td>+3</td>
<td>+3</td>
</tr>
<tr class="even">
<td>W6</td>
<td>−3</td>
<td>0</td>
<td>+2</td>
</tr>
<tr class="odd">
<td>W7</td>
<td>−2</td>
<td>+1</td>
<td>+3</td>
</tr>
<tr class="even">
<td>W8</td>
<td>+3</td>
<td>0</td>
<td>−2</td>
</tr>
<tr class="odd">
<td>W9</td>
<td>+1</td>
<td>+3</td>
<td>+1</td>
</tr>
<tr class="even">
<td>W10</td>
<td>−1</td>
<td>−3</td>
<td>−1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The patterns are worth a quick read: W1 / W2 / W5 are near-parallel moves; W3 / W4 add a gentle slope twist on top of a parallel move; W6 / W7 / W8 are steepeners and a flattener; W9 / W10 are curvature moves where the belly (5y) leads. This mix of factor types is what produces the three-factor decomposition that follows.</p>
<div id="fig-raw-scatter" class="quarto-float quarto-figure quarto-figure-center anchored" alt="3D scatter plot of 10 weekly observations on the 2y, 5y, 10y tenors, with the sample mean shown as a hollow circle near the origin">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-raw-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="raw_scatter_3d.png" class="img-fluid figure-img" alt="3D scatter plot of 10 weekly observations on the 2y, 5y, 10y tenors, with the sample mean shown as a hollow circle near the origin">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-raw-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: 10 weekly observations and their sample mean in (2y, 5y, 10y) space. The points spread along a clear diagonal — which is the geometric signature of the strong cross-tenor correlation that PCA is built to address.
</figcaption>
</figure>
</div>
<p>The sample means are 0.30 bps on the 2y, 0.60 bps on the 5y, 0.80 bps on the 10y. As in the 2D case, PCA operates on deviations from the mean; the centered data is the raw values minus this vector. The covariance computations in §3 use the centered data.</p>
</section>
<section id="the-data-is-highly-correlated" class="level2">
<h2 class="anchored" data-anchor-id="the-data-is-highly-correlated">The data is highly correlated</h2>
<p>The sample correlation matrix is:</p>
<p><span class="math display">\[
\rho = \begin{bmatrix} 1.000 &amp; 0.856 &amp; 0.651 \\ 0.856 &amp; 1.000 &amp; 0.893 \\ 0.651 &amp; 0.893 &amp; 1.000 \end{bmatrix}
\]</span></p>
<p>Adjacent tenors are correlated above 0.85; even the most distant pair (2y vs 10y) is at 0.65. This is the empirical condition that makes independent stress testing on the raw tenors unrealistic. Shocking the 2y up while holding the 10y fixed produces a scenario that essentially never occurs in the sample. PCA addresses this by re-expressing the data in three orthogonal directions, each of which can be shocked independently while the result, when projected back, still respects the historical correlations.</p>
</section>
<section id="extracting-the-principal-components" class="level2">
<h2 class="anchored" data-anchor-id="extracting-the-principal-components">Extracting the principal components</h2>
<p>The sample covariance matrix (using the n − 1 = 9 denominator, matching R’s <code>cov()</code> defaults) is:</p>
<p><span class="math display">\[
\Sigma = \begin{bmatrix} 14.900 &amp; 11.356 &amp; 7.844 \\ 11.356 &amp; 11.822 &amp; 9.578 \\ 7.844 &amp; 9.578 &amp; 9.733 \end{bmatrix}
\]</span></p>
<p>Solving det(Σ − λI) = 0 gives three eigenvalues and three corresponding eigenvectors:</p>
<div id="tbl-eig" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-eig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Eigendecomposition of the 3×3 sample covariance matrix.
</figcaption>
<div aria-describedby="tbl-eig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 16%">
<col style="width: 40%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Eigenvalue</th>
<th>Eigenvector</th>
<th>Variance share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PC1 (Level)</td>
<td>31.66</td>
<td>[+0.634, +0.599, +0.489]</td>
<td>86.85%</td>
</tr>
<tr class="even">
<td>PC2 (Slope)</td>
<td>4.26</td>
<td>[−0.702, +0.181, +0.689]</td>
<td>11.70%</td>
</tr>
<tr class="odd">
<td>PC3 (Curvature)</td>
<td>0.53</td>
<td>[+0.324, −0.780, +0.535]</td>
<td>1.45%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The three loadings tell the entire story of why these factors are called what they are called.</p>
<div id="fig-loadings" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three-panel bar chart. PC1 panel shows three positive bars roughly equal in height. PC2 panel shows a negative bar at 2y, near-zero at 5y, positive at 10y. PC3 panel shows positive bars at 2y and 10y and a large negative bar at 5y.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-loadings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pc_loadings.png" class="img-fluid figure-img" alt="Three-panel bar chart. PC1 panel shows three positive bars roughly equal in height. PC2 panel shows a negative bar at 2y, near-zero at 5y, positive at 10y. PC3 panel shows positive bars at 2y and 10y and a large negative bar at 5y.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-loadings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: PC loadings across the three tenors. Each panel is one principal component; the bars show how that component loads on each tenor. The sign patterns are the canonical L/S/C signatures: Level (all positive, gentle taper), Slope (short and long opposite, belly small), Curvature (ends positive, belly negative).
</figcaption>
</figure>
</div>
<p><strong>PC1 is Level.</strong> All three loadings are positive and similar in magnitude (+0.63, +0.60, +0.49). A positive PC1 score corresponds to all three tenors rising, with the short end rising slightly more than the long end. This is what fixed-income practitioners mean by a “parallel shift” — approximately parallel, not literally parallel, because the loadings are not exactly equal.</p>
<p><strong>PC2 is Slope.</strong> The 2y loading is large and negative (−0.70), the 10y loading is large and positive (+0.69), and the 5y loading is small (+0.18). A positive PC2 score corresponds to the short end falling and the long end rising — a steepener. A negative PC2 score is a flattener. The belly tenor is approximately a pivot point. This is the textbook slope signature.</p>
<p><strong>PC3 is Curvature.</strong> The 2y and 10y loadings are positive (+0.32, +0.54), the 5y loading is large and negative (−0.78). A positive PC3 score corresponds to the ends rising while the belly falls — a “butterfly” move where the curve becomes more bowed. A negative PC3 score is the opposite (“butterfly down” or de-bowing).</p>
<p>The variance shares 86.85% / 11.70% / 1.45% are a clean L/S/C hierarchy. In real-world yield curve data with longer samples and more tenors, <span class="citation" data-cites="litterman1991">Litterman and Scheinkman (<a href="#ref-litterman1991" role="doc-biblioref">1991</a>)</span> documented similar three-factor structure explaining roughly 95% of variance in U.S. Treasury yields; the canonical published proportions are roughly 90% / 7% / 2%. The toy sample above happens to land close to that.</p>
<p>Two conventions affect reproducibility. Eigenvectors are defined up to sign, so software may return any of the eigenvectors above with all signs flipped — the result is the same direction in space and does not change any downstream analysis. The conventions adopted here are: PC1’s average loading is positive, PC2’s long-end loading is positive (so positive PC2 = steepener), and PC3’s belly loading is negative (so positive PC3 = ends-up butterfly). The covariance estimator uses the n − 1 = 9 denominator, matching R’s defaults; <code>numpy.cov</code> requires <code>ddof=1</code> to match.</p>
</section>
<section id="before-and-after-pca" class="level2">
<h2 class="anchored" data-anchor-id="before-and-after-pca">Before and after PCA</h2>
<p>The forward operation of PCA can be drawn directly. The “before” view is the centered data in (2y, 5y, 10y) space; the “after” view is the same observations re-expressed in (PC1, PC2, PC3) score coordinates.</p>
<div id="fig-before-after" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two 3D scatter plots side by side. Left plot shows 10 observations on near-diagonal pattern in centered tenor space. Right plot shows the same 10 observations spread more evenly in PC score space.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-before-after-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="before_after_pca.png" class="img-fluid figure-img" alt="Two 3D scatter plots side by side. Left plot shows 10 observations on near-diagonal pattern in centered tenor space. Right plot shows the same 10 observations spread more evenly in PC score space.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-before-after-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Before and after PCA. <strong>Left:</strong> centered weekly changes spread along a clear diagonal, reflecting the strong correlation (max pairwise correlation 0.89) between the three tenors. <strong>Right:</strong> after projection onto the principal components, the data fills (PC1, PC2, PC3) space more evenly — and crucially, the off-diagonal correlations between PC scores are zero by construction (the largest off-diagonal correlation is about 5 × 10⁻¹⁶, which is numerical floor).
</figcaption>
</figure>
</div>
<p>The titles on the two panels carry the headline result: pairwise correlations between centered tenors are as high as 0.89, while the corresponding correlations between PC scores are zero (to numerical precision). This is exactly what PCA is designed to do — the rotation re-expresses the data in a coordinate system where the new axes are statistically independent (uncorrelated, technically).</p>
</section>
<section id="pca-as-variance-aligned-axes" class="level2">
<h2 class="anchored" data-anchor-id="pca-as-variance-aligned-axes">PCA as variance-aligned axes</h2>
<p>In two dimensions PCA can be visualised as a literal rotation that maximises horizontal variance. In three dimensions the same idea applies, but it cannot be reduced to a single rotation angle — a 3D rotation has three angles, not one. What remains true and visualisable is this: <strong>the eigenvectors of the covariance matrix are the variance-aligned axes of the data cloud, drawn through its mean.</strong></p>
<p>The animation below shows the 10-week cloud with the three eigenvector axes drawn through the sample mean, each scaled to ±1 standard deviation of its principal component. The camera orbits around the cloud so the three-dimensional geometry can be seen from multiple angles. The PC1 axis (rust) cleanly traces the long spine of the data; PC2 (green) is the second-longest axis perpendicular to PC1; PC3 (gold) is so short it is almost invisible at the +1 SD endpoint, which is the geometric statement that PC3 explains only 1.45% of variance.</p>
<div id="fig-rotation" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Animated GIF showing 3D scatter of 10 weekly observations rotating around the vertical axis, with three colored line segments (PC1 rust, PC2 green, PC3 gold) extending from the sample mean along the principal directions.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rotation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="rotation_animation.gif" class="img-fluid figure-img" alt="Animated GIF showing 3D scatter of 10 weekly observations rotating around the vertical axis, with three colored line segments (PC1 rust, PC2 green, PC3 gold) extending from the sample mean along the principal directions.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rotation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Rotating viewpoint around the 10-week cloud. The three line segments are the PC1, PC2 and PC3 eigenvectors drawn through the sample mean, each extending ±1 standard deviation along that component’s direction.
</figcaption>
</figure>
</div>
<p>The relative lengths of the three line segments encode the variance hierarchy directly: PC1 is the longest, PC2 is roughly a third its length (since √(11.70/86.85) ≈ 0.37), and PC3 is roughly one-eighth its length (since √(1.45/86.85) ≈ 0.13). The eigenvalues and the visible axis lengths in the animation are the same information rendered two different ways.</p>
</section>
<section id="the-pca-scores" class="level2">
<h2 class="anchored" data-anchor-id="the-pca-scores">The PCA scores</h2>
<p>Projecting each week’s centered observation onto the three eigenvectors gives the PCA scores — the coordinates of each week in the (PC1, PC2, PC3) system.</p>
<div id="tbl-scores" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-scores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: PCA scores: the same 10 weeks in (PC1, PC2, PC3) coordinates.
</figcaption>
<div aria-describedby="tbl-scores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Week</th>
<th>PC1 (Level)</th>
<th>PC2 (Slope)</th>
<th>PC3 (Curvature)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>W1</td>
<td>+7.669</td>
<td>+0.393</td>
<td>+0.340</td>
</tr>
<tr class="even">
<td>W2</td>
<td>−7.829</td>
<td>−1.124</td>
<td>−0.376</td>
</tr>
<tr class="odd">
<td>W3</td>
<td>+7.815</td>
<td>−0.998</td>
<td>+0.129</td>
</tr>
<tr class="even">
<td>W4</td>
<td>−7.974</td>
<td>+0.267</td>
<td>−0.164</td>
</tr>
<tr class="odd">
<td>W5</td>
<td>+4.225</td>
<td>+0.056</td>
<td>+0.181</td>
</tr>
<tr class="even">
<td>W6</td>
<td>−1.867</td>
<td>+3.034</td>
<td>+0.041</td>
</tr>
<tr class="odd">
<td>W7</td>
<td>−0.145</td>
<td>+3.202</td>
<td>+0.121</td>
</tr>
<tr class="even">
<td>W8</td>
<td>−0.014</td>
<td>−3.933</td>
<td>−0.156</td>
</tr>
<tr class="odd">
<td>W9</td>
<td>+1.979</td>
<td>+0.082</td>
<td>−1.538</td>
</tr>
<tr class="even">
<td>W10</td>
<td>−3.861</td>
<td>−0.981</td>
<td>+1.423</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The structure of the table tells the same story as the loading patterns. The big level moves (W1 to W4) have PC1 scores around ±8 and small PC2 / PC3 scores. The pure slope weeks (W6, W7, W8) have small PC1 scores but PC2 scores of ±3. The two curvature weeks (W9, W10) have small PC1 / PC2 scores but the largest absolute PC3 scores in the sample. The decomposition has cleanly separated the three types of move into three orthogonal coordinates.</p>
<p>A direct verification of one row: for W6, the centered observation is (−3.30, −0.60, +1.20). The PC2 score is (−3.30) × (−0.702) + (−0.60) × 0.181 + (1.20) × 0.689 = 2.317 − 0.109 + 0.827 = 3.034. The other entries in the row check the same way.</p>
</section>
<section id="reverse-construction-building-stress-scenarios" class="level2">
<h2 class="anchored" data-anchor-id="reverse-construction-building-stress-scenarios">Reverse construction: building stress scenarios</h2>
<p>The forward use of PCA produces scores from observations. The reverse use — the one that matters for stress testing — starts from a hypothetical PC score and projects back to a tenor-space yield change:</p>
<p><span class="math display">\[
\text{Stressed change} = \text{Mean} + (\text{Shock magnitude}) \times \text{Eigenvector}
\]</span></p>
<p>Shock magnitudes are calibrated in standard deviations of the relevant PC. The standard deviations are the square roots of the eigenvalues:</p>
<ul>
<li>1 SD of PC1 (Level) = √31.66 ≈ 5.627 bps</li>
<li>1 SD of PC2 (Slope) = √4.26 ≈ 2.065 bps</li>
<li>1 SD of PC3 (Curvature) = √0.53 ≈ 0.728 bps</li>
</ul>
<p>The three standard deviations differ by a factor of roughly 8: Level is about 2.7× larger than Slope, which is about 2.8× larger than Curvature. This automatic scaling is one of the reasons PCA is useful for stress testing — the eigenvalues themselves tell the modeller that “1 SD of curvature” is a much smaller event in bps than “1 SD of level”, without anyone having to choose those scales by hand.</p>
<p>The “1 SD” choice here is for illustration. Real regulatory frameworks use higher percentiles. Solvency II uses 99.5% one-year Value-at-Risk, which is roughly 2.58 SD under a Gaussian assumption. The mechanism is identical; only the multiplier changes.</p>
<section id="scenario-a-a-level-shock-1-sd-on-pc1" class="level3">
<h3 class="anchored" data-anchor-id="scenario-a-a-level-shock-1-sd-on-pc1">Scenario A: a level shock (+1 SD on PC1)</h3>
<p>Shocking PC1 by +1 SD (5.627) and holding PC2 and PC3 at zero produces:</p>
<div id="tbl-scenario-a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-scenario-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Scenario A: +1 SD shock on PC1 (Level).
</figcaption>
<div aria-describedby="tbl-scenario-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tenor</th>
<th>Mean change</th>
<th>PC1 impact</th>
<th>Stressed change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2y</td>
<td>+0.30</td>
<td>5.627 × 0.634 = +3.57</td>
<td>+3.87</td>
</tr>
<tr class="even">
<td>5y</td>
<td>+0.60</td>
<td>5.627 × 0.599 = +3.37</td>
<td>+3.97</td>
</tr>
<tr class="odd">
<td>10y</td>
<td>+0.80</td>
<td>5.627 × 0.489 = +2.75</td>
<td>+3.55</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>All three tenors rise by roughly 3–4 bps, with the short end rising slightly more than the long end. This is a coherent “parallel up” stress — approximately parallel, in the same approximate sense as the PC1 loadings themselves are approximately equal. The 0.32 bp difference between the 2y and 10y stress impacts reflects the loading taper (+0.634 vs +0.489).</p>
</section>
<section id="scenario-b-a-slope-shock-1-sd-on-pc2" class="level3">
<h3 class="anchored" data-anchor-id="scenario-b-a-slope-shock-1-sd-on-pc2">Scenario B: a slope shock (+1 SD on PC2)</h3>
<p>Shocking PC2 by +1 SD (2.065) and holding PC1 and PC3 at zero produces:</p>
<div id="tbl-scenario-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-scenario-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Scenario B: +1 SD shock on PC2 (Slope).
</figcaption>
<div aria-describedby="tbl-scenario-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tenor</th>
<th>Mean change</th>
<th>PC2 impact</th>
<th>Stressed change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2y</td>
<td>+0.30</td>
<td>2.065 × (−0.702) = −1.45</td>
<td>−1.15</td>
</tr>
<tr class="even">
<td>5y</td>
<td>+0.60</td>
<td>2.065 × 0.181 = +0.37</td>
<td>+0.97</td>
</tr>
<tr class="odd">
<td>10y</td>
<td>+0.80</td>
<td>2.065 × 0.689 = +1.42</td>
<td>+2.22</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The 2y falls, the 5y barely moves, the 10y rises — a clean steepener. The 10y-vs-2y spread widens by 2.87 bps relative to the unstressed baseline. This is what a +1 SD slope shock looks like in tenor space: not just “everything rises” but a structurally different curve shape.</p>
</section>
<section id="scenario-c-a-curvature-shock-1-sd-on-pc3" class="level3">
<h3 class="anchored" data-anchor-id="scenario-c-a-curvature-shock-1-sd-on-pc3">Scenario C: a curvature shock (+1 SD on PC3)</h3>
<p>Shocking PC3 by +1 SD (0.728) and holding PC1 and PC2 at zero produces:</p>
<div id="tbl-scenario-c" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-scenario-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Scenario C: +1 SD shock on PC3 (Curvature).
</figcaption>
<div aria-describedby="tbl-scenario-c-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tenor</th>
<th>Mean change</th>
<th>PC3 impact</th>
<th>Stressed change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2y</td>
<td>+0.30</td>
<td>0.728 × 0.324 = +0.24</td>
<td>+0.54</td>
</tr>
<tr class="even">
<td>5y</td>
<td>+0.60</td>
<td>0.728 × (−0.780) = −0.57</td>
<td>+0.03</td>
</tr>
<tr class="odd">
<td>10y</td>
<td>+0.80</td>
<td>0.728 × 0.535 = +0.39</td>
<td>+1.19</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The ends rise, the belly essentially holds still — a “butterfly” move in which the curve becomes more bowed. The magnitudes are small (the largest impact is +0.57 bps on the 5y) because the curvature standard deviation is small, again reflecting the eigenvalue automatically setting the scale.</p>
<p>The new content in this article relative to the 2D version is the existence of Scenario C. With only two tenors, a curvature shock is not even definable. With three tenors, it exists, has the canonical sign pattern, and its scale is set automatically by the data.</p>
</section>
<section id="stresses-in-the-context-of-the-sample" class="level3">
<h3 class="anchored" data-anchor-id="stresses-in-the-context-of-the-sample">Stresses in the context of the sample</h3>
<p>All three stress scenarios can be plotted in the original yield-change space alongside the 10 observed weeks and the sample mean.</p>
<div id="fig-stress-overlay" class="quarto-float quarto-figure quarto-figure-center anchored" alt="3D scatter showing 10 observed weeks as blue dots, sample mean as hollow ring, and three stress points: rust diamond for Stress A relatively far from mean, green triangle for Stress B closer to mean, gold square essentially on top of the mean.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-overlay-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="stress_overlay.png" class="img-fluid figure-img" alt="3D scatter showing 10 observed weeks as blue dots, sample mean as hollow ring, and three stress points: rust diamond for Stress A relatively far from mean, green triangle for Stress B closer to mean, gold square essentially on top of the mean.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-overlay-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Three stress scenarios overlaid on the 10 weekly observations. Stress A (level) sits well into the upper-right region of the cloud. Stress B (slope) is closer to the mean. Stress C (curvature) is essentially on top of the mean. The relative distances from the mean reflect the standard-deviation hierarchy: 5.63 / 2.07 / 0.73 bps.
</figcaption>
</figure>
</div>
<p>The three stress points are not arbitrary positions; each is at the +1 SD endpoint along one of the three PC axes drawn in the rotation animation in §5. The fact that Stress A is visibly far from the mean while Stress C is visibly on top of the mean is the variance hierarchy 86.85% / 11.70% / 1.45% rendered geometrically.</p>
</section>
<section id="each-observation-before-and-after-each-shock" class="level3">
<h3 class="anchored" data-anchor-id="each-observation-before-and-after-each-shock">Each observation before and after each shock</h3>
<p>The shock vectors that define Scenarios A, B and C are fixed regardless of where they are applied. Adding them to the sample mean produces the three single-point scenarios above. Adding the same vector to each of the 10 observed weeks produces three full clouds of stressed weeks — one cloud per shock — which is the scenario-based stress framework where each historical week is treated as a possible current state.</p>
<div id="tbl-per-day-stress" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-per-day-stress-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: The 10 weeks before and after each stress. Same shock vector added to each week.
</figcaption>
<div aria-describedby="tbl-per-day-stress-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 31%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Week</th>
<th>Original (2y, 5y, 10y)</th>
<th>+PC1 (Level)</th>
<th>+PC2 (Slope)</th>
<th>+PC3 (Curvature)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>W1</td>
<td>(+5.00, +5.00, +5.00)</td>
<td>(+8.57, +8.37, +7.75)</td>
<td>(+3.55, +5.37, +6.42)</td>
<td>(+5.24, +4.43, +5.39)</td>
</tr>
<tr class="even">
<td>W2</td>
<td>(−4.00, −4.00, −4.00)</td>
<td>(−0.43, −0.63, −1.25)</td>
<td>(−5.45, −3.63, −2.58)</td>
<td>(−3.76, −4.57, −3.61)</td>
</tr>
<tr class="odd">
<td>W3</td>
<td>(+6.00, +5.00, +4.00)</td>
<td>(+9.57, +8.37, +6.75)</td>
<td>(+4.55, +5.37, +5.42)</td>
<td>(+6.24, +4.43, +4.39)</td>
</tr>
<tr class="even">
<td>W4</td>
<td>(−5.00, −4.00, −3.00)</td>
<td>(−1.43, −0.63, −0.25)</td>
<td>(−6.45, −3.63, −1.58)</td>
<td>(−4.76, −4.57, −2.61)</td>
</tr>
<tr class="odd">
<td>W5</td>
<td>(+3.00, +3.00, +3.00)</td>
<td>(+6.57, +6.37, +5.75)</td>
<td>(+1.55, +3.37, +4.42)</td>
<td>(+3.24, +2.43, +3.39)</td>
</tr>
<tr class="even">
<td>W6</td>
<td>(−3.00, +0.00, +2.00)</td>
<td>(+0.57, +3.37, +4.75)</td>
<td>(−4.45, +0.37, +3.42)</td>
<td>(−2.76, −0.57, +2.39)</td>
</tr>
<tr class="odd">
<td>W7</td>
<td>(−2.00, +1.00, +3.00)</td>
<td>(+1.57, +4.37, +5.75)</td>
<td>(−3.45, +1.37, +4.42)</td>
<td>(−1.76, +0.43, +3.39)</td>
</tr>
<tr class="even">
<td>W8</td>
<td>(+3.00, +0.00, −2.00)</td>
<td>(+6.57, +3.37, +0.75)</td>
<td>(+1.55, +0.37, −0.58)</td>
<td>(+3.24, −0.57, −1.61)</td>
</tr>
<tr class="odd">
<td>W9</td>
<td>(+1.00, +3.00, +1.00)</td>
<td>(+4.57, +6.37, +3.75)</td>
<td>(−0.45, +3.37, +2.42)</td>
<td>(+1.24, +2.43, +1.39)</td>
</tr>
<tr class="even">
<td>W10</td>
<td>(−1.00, −3.00, −1.00)</td>
<td>(+2.57, +0.37, +1.75)</td>
<td>(−2.45, −2.63, +0.42)</td>
<td>(−0.76, −3.57, −0.61)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The values are constructed entry by entry. For W8 under +PC1: original (3, 0, −2) plus shock (+3.57, +3.37, +2.75) gives (+6.57, +3.37, +0.75). For W8 under +PC2: original (3, 0, −2) plus shock (−1.45, +0.37, +1.42) gives (+1.55, +0.37, −0.58). For W8 under +PC3: original (3, 0, −2) plus shock (+0.24, −0.57, +0.39) gives (+3.24, −0.57, −1.61). The same simple addition produces every other cell.</p>
<div id="fig-before-after-stress" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three 3D scatter plots side by side. Left panel shows 10 original blue dots and 10 stressed rust diamonds connected by grey lines, with all diamonds shifted up-and-right. Middle panel shows tilting pattern. Right panel shows stressed gold squares essentially overlapping the originals.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-before-after-stress-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="before_after_stress.png" class="img-fluid figure-img" alt="Three 3D scatter plots side by side. Left panel shows 10 original blue dots and 10 stressed rust diamonds connected by grey lines, with all diamonds shifted up-and-right. Middle panel shows tilting pattern. Right panel shows stressed gold squares essentially overlapping the originals.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-before-after-stress-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: The 10 weeks before and after each stress shock. Left to right: Level, Slope, Curvature. Each panel shows the original observations (blue circles), the stressed observations (coloured markers), and grey segments connecting each original to its stressed counterpart. The Level panel shows a uniform shift toward higher yields. The Slope panel shows the cloud tilting — 2y values fall and 10y values rise. The Curvature panel shows almost no movement, because the shock vector is small at this scale.
</figcaption>
</figure>
</div>
<p>A consistency check: the mean of the +PC1 stressed cloud is (3.87, 3.97, 3.55), which is exactly the Scenario A point from §7.1. The mean of the +PC2 stressed cloud is (−1.15, 0.97, 2.22), which is Scenario B. The mean of the +PC3 stressed cloud is (0.54, 0.03, 1.19), which is Scenario C. This is mechanical — translating every point by the same vector translates the mean by that vector — but it confirms that the per-week table and the per-scenario tables are saying the same thing from different starting points.</p>
</section>
</section>
<section id="sec-limits" class="level2">
<h2 class="anchored" data-anchor-id="sec-limits">Limitations of this example</h2>
<p>The sample is 10 weeks. This is a small sample for estimating a 3×3 covariance matrix — a serious empirical PCA on yield curves would use months or years of data, not weeks. The eigenvalues and eigenvectors above are reasonable for a textbook exposition, but readers should not infer that “PC3 explains 1.45% of variance” or similar specifics generalise to any real dataset. What does generalise is the qualitative L/S/C structure: in nearly every large sample of historical yield curve changes, the three leading principal components have approximately the sign patterns shown in <a href="#fig-loadings" class="quarto-xref">Figure&nbsp;2</a>.</p>
<p>The data is engineered. As noted in the introduction, the 10 weeks were chosen to produce a clean three-factor decomposition. On real-world data the loadings have measurement noise, the variance shares vary across periods, and occasionally PC2 and PC3 can mix or swap order. The exposition above shows the structure that practitioners <em>expect</em>; a real dataset would show that structure with imperfections.</p>
<p>The article does not address an important real-world question: PCA on yield <em>changes</em> versus PCA on yield <em>levels</em>. The two procedures produce different eigenvectors and different interpretations. The L/S/C decomposition is a property of changes, not levels. The Litterman–Scheinkman analysis, and virtually all regulatory frameworks built on it, operate on changes. This article follows that convention without further discussion.</p>
</section>
<section id="stresses-as-yield-curve-transformations" class="level2">
<h2 class="anchored" data-anchor-id="stresses-as-yield-curve-transformations">Stresses as yield-curve transformations</h2>
<p>So far the shocks have been described as vectors in (2y, 5y, 10y) coordinate space, and the figures showing them have used 3D scatter plots. That treatment is mathematically clean but pedagogically indirect — it asks readers to translate from coordinate triples back into “what does the actual yield curve look like.” This section closes that gap by visualising the shocks as curve transformations.</p>
<p>The PCA itself is unchanged: the article still works on yield <em>changes</em>, the eigenvectors and stress vectors are exactly as computed above. The only addition is an arbitrary baseline yield-level curve, used purely to anchor the visualisation. The baseline values are not derived from the data and have no relationship to the PCA; a different baseline would shift the curves bodily up or down but would not change any conclusion about the shocks themselves.</p>
<p>The illustrative baseline is:</p>
<div id="tbl-baseline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-baseline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Illustrative baseline yield curve. These values are arbitrary; they exist only to make the curve-transformation figures readable.
</figcaption>
<div aria-describedby="tbl-baseline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tenor</th>
<th>Baseline yield (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2y</td>
<td>2.00</td>
</tr>
<tr class="even">
<td>5y</td>
<td>2.50</td>
</tr>
<tr class="odd">
<td>10y</td>
<td>3.00</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The “stressed mean” yield level at each tenor is then <code>baseline + mean change + shock impact</code>, all converted to consistent units. With the baseline at percentage scale (2.00, 2.50, 3.00) and the mean change plus shock impact in basis points, this is a small adjustment — roughly 3–4 bps at most.</p>
<div id="fig-curve-shock-mean" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two-panel figure. Left panel shows four yield-level curves nearly on top of each other, going from 2% at 2y to 3% at 10y. Right panel shows three shock impact curves on a tighter scale, clearly showing the Level (mostly flat positive), Slope (negative-to-positive ascending), and Curvature (positive-negative-positive shape) signatures.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-curve-shock-mean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="curve_shock_mean.png" class="img-fluid figure-img" alt="Two-panel figure. Left panel shows four yield-level curves nearly on top of each other, going from 2% at 2y to 3% at 10y. Right panel shows three shock impact curves on a tighter scale, clearly showing the Level (mostly flat positive), Slope (negative-to-positive ascending), and Curvature (positive-negative-positive shape) signatures.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-curve-shock-mean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Stress scenarios as yield-curve transformations. <strong>Left:</strong> the baseline level curve and the three stressed mean curves. At a baseline of 2-3% with 1 SD shocks of 3-4 bps, the four curves are visually close — which is the honest geometric statement that 1 SD shocks are small relative to the level. <strong>Right:</strong> the same three shocks plotted as deviations from baseline, on a tight bps axis where the L/S/C signatures become unmistakable: Level shifts everything up, Slope tilts the curve (2y down, 10y up), Curvature bows the belly down relative to the ends.
</figcaption>
</figure>
</div>
<p>The left panel says one important thing the article has not stated before: a 1 SD shock is small in absolute terms. The four lines nearly overlap because three or four basis points is a small movement relative to the 200–300 bps baseline level. The right panel is where the shock structure becomes visible. The three coloured lines on the right are exactly the L/S/C signatures from the bar chart in §3, re-drawn as curves over tenor: PC1 is approximately flat-positive (parallel-up shift); PC2 ascends from negative at the short end to positive at the long end (steepener); PC3 has the characteristic ∨-shape with the belly below the ends (butterfly).</p>
<p>The per-week version of the same picture extends the cloud-translation idea from §8 to curve-space. For each shock, the 10 baseline weekly level curves (constructed as baseline + observed change) are shown in faint blue, and the same 10 weeks after the shock is added are shown in the shock’s colour. The y-axis is auto-scaled per panel so the shock — which is only 3-4 bps on a baseline of 200-300 bps — remains visible.</p>
<div id="fig-curves-before-after" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three-panel figure showing 10 baseline weekly level curves in faint blue and 10 stressed curves in the shock colour in each panel, all in percent. Level panel shows uniform vertical shift of about 3 bps. Slope panel shows tilt with 2y end falling and 10y end rising. Curvature panel shows belly dipping slightly relative to ends.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-curves-before-after-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="curves_before_after_stress.png" class="img-fluid figure-img" alt="Three-panel figure showing 10 baseline weekly level curves in faint blue and 10 stressed curves in the shock colour in each panel, all in percent. Level panel shows uniform vertical shift of about 3 bps. Slope panel shows tilt with 2y end falling and 10y end rising. Curvature panel shows belly dipping slightly relative to ends.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-curves-before-after-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: The 10 weekly <strong>level</strong> curves before and after each shock. <strong>Left (Level):</strong> every weekly curve sits roughly 3 bps higher after the +PC1 shock; rust diamonds are clearly above blue circles at every tenor. <strong>Middle (Slope):</strong> the curves tilt; at the 2y the green triangles sit below blue (the 2y falls by ~1.5 bps), at the 10y they sit above (the 10y rises by ~1.4 bps). <strong>Right (Curvature):</strong> at the 5y belly the gold squares dip slightly below blue (belly falls ~0.6 bps), while at the 2y and 10y ends they sit slightly above; the bowing is subtle but consistent across all 10 weeks.
</figcaption>
</figure>
</div>
<p>The L/S/C signatures are now visible per week rather than only on the mean, and in the same units (percent yield) that practitioners actually read curves in. Every blue curve has a coloured counterpart that differs from it by exactly the shock vector — uniformly across all weeks, which is the defining property of a factor shock. The y-axis is in percent and the visible separations between blue and coloured curves are the few-bps shocks rendered at level scale.</p>
<p>The honest visual cost of plotting in level rather than change space is that the shock is much smaller than the natural week-to-week spread of the baseline curves. The level-space view answers “what does the stressed yield curve look like next to the baseline curve?”, which is what a trader or risk manager would actually compare. The bps-axis view of the same shocks — exactly the L/S/C signatures from the bar chart in §3 — is shown in the right panel of <a href="#fig-curve-shock-mean" class="quarto-xref">Figure&nbsp;7</a> above.</p>
<p>A note worth stating explicitly: this section visualises <em>changes</em> on top of an invented level baseline. It is not PCA on yield levels. PCA on levels is a different procedure, produces different eigenvectors, and is methodologically inappropriate for stress testing — as noted in <a href="#sec-limits">§ 10</a> below. The visualisation here is a convenience for reading the shocks as curve shapes, not a recommendation for the underlying technique.</p>
</section>
<section id="sec-var" class="level2">
<h2 class="anchored" data-anchor-id="sec-var">A 99.5% VaR stress example</h2>
<p>Every stress shown so far has been at the +1 SD severity. This is illustrative but not what any regulator asks for. Solvency II and most modern capital regimes work in terms of 99.5% one-year Value-at-Risk — the loss that would not be exceeded in 199 years out of 200.</p>
<p>Under a Gaussian assumption, the 99.5% one-year VaR corresponds to a multiplier of <span class="math inline">\(z_{0.995} = 2.576\)</span> standard deviations. Replacing the +1 SD multiplier from §8 with k = 2.576 leaves the PCA machinery untouched and rescales the shock vectors by exactly the same factor. This is the central reason PCA is convenient for capital modelling: changing severity is one multiplier, not a re-derivation.</p>
<p>Regulatory stress testing is two-sided. A bond portfolio that is hurt by a rate rise is helped by a rate fall, and vice versa; capital requirements consider the worst case across both directions. The same logic extends to slope and curvature. We therefore construct <strong>six</strong> scenarios at the 99.5% severity — one for each direction on each of the three PCs.</p>
<p>The shock magnitudes are:</p>
<div id="tbl-var-shocks" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-var-shocks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: 99.5% VaR shock impacts on each tenor. Each row is k = 2.576 × SD × eigenvector for that PC, with both sign directions.
</figcaption>
<div aria-describedby="tbl-var-shocks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 17%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Scenario</th>
<th>k × SD</th>
<th>Per-tenor impact (2y, 5y, 10y) bps</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>+k SD PC1 (Level up)</td>
<td>+14.49 bps</td>
<td>(+9.20, +8.68, +7.08)</td>
</tr>
<tr class="even">
<td>−k SD PC1 (Level down)</td>
<td>−14.49 bps</td>
<td>(−9.20, −8.68, −7.08)</td>
</tr>
<tr class="odd">
<td>+k SD PC2 (Steepener)</td>
<td>+5.32 bps</td>
<td>(−3.73, +0.97, +3.66)</td>
</tr>
<tr class="even">
<td>−k SD PC2 (Flattener)</td>
<td>−5.32 bps</td>
<td>(+3.73, −0.97, −3.66)</td>
</tr>
<tr class="odd">
<td>+k SD PC3 (Curvature up)</td>
<td>+1.87 bps</td>
<td>(+0.61, −1.46, +1.00)</td>
</tr>
<tr class="even">
<td>−k SD PC3 (Curvature down)</td>
<td>−1.87 bps</td>
<td>(−0.61, +1.46, −1.00)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Applied to the same baseline (2.00, 2.50, 3.00) % from §10 and the sample mean drift, the resulting stressed yield-curve levels are:</p>
<div id="tbl-var-levels" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-var-levels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Stressed yield-curve levels at the 99.5% VaR severity.
</figcaption>
<div aria-describedby="tbl-var-levels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Scenario</th>
<th>Stressed (2y, 5y, 10y) %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Baseline + mean change</td>
<td>(2.003, 2.506, 3.008)</td>
</tr>
<tr class="even">
<td>+k SD PC1 (Level up)</td>
<td>(2.095, 2.593, 3.079)</td>
</tr>
<tr class="odd">
<td>−k SD PC1 (Level down)</td>
<td>(1.911, 2.419, 2.937)</td>
</tr>
<tr class="even">
<td>+k SD PC2 (Steepener)</td>
<td>(1.966, 2.516, 3.045)</td>
</tr>
<tr class="odd">
<td>−k SD PC2 (Flattener)</td>
<td>(2.040, 2.496, 2.971)</td>
</tr>
<tr class="even">
<td>+k SD PC3 (Curvature up)</td>
<td>(2.009, 2.491, 3.018)</td>
</tr>
<tr class="odd">
<td>−k SD PC3 (Curvature down)</td>
<td>(1.997, 2.521, 2.998)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-var" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Single-panel level-curves figure showing seven curves on the (2y, 5y, 10y) tenor grid: baseline plus six 99.5% VaR stress scenarios. Rust diamond and rust triangle for Level up and down. Green up-triangle and green down-triangle for Steepener and Flattener. Gold square and gold plus for Curvature up and down. Curves span roughly 1.77% to 3.20% across the tenors.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="var_995_stress.png" class="img-fluid figure-img" alt="Single-panel level-curves figure showing seven curves on the (2y, 5y, 10y) tenor grid: baseline plus six 99.5% VaR stress scenarios. Rust diamond and rust triangle for Level up and down. Green up-triangle and green down-triangle for Steepener and Flattener. Gold square and gold plus for Curvature up and down. Curves span roughly 1.77% to 3.20% across the tenors.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Six 99.5% VaR stress scenarios drawn as yield-level curves on the same baseline. Solid lines are positive-direction shocks (+k SD); dashed lines are negative-direction shocks (−k SD). Rust = Level, Green = Slope, Gold = Curvature. The baseline-plus-mean (open black circles) is centred among the six stressed curves. The vertical spread between Level-up and Level-down is the widest — roughly 18 bps at the 2y — reflecting that PC1 has by far the largest standard deviation.
</figcaption>
</figure>
</div>
<p>Three observations make this figure useful for capital modelling intuition.</p>
<p>First, the <strong>Level scenarios dominate the spread of outcomes</strong>. The two rust curves are the highest and lowest of the six at every tenor. This is the geometric reflection of PC1’s 86.85% variance share: a 99.5% level shock is roughly 2.7 times the magnitude of a 99.5% slope shock, and roughly 7.7 times the magnitude of a 99.5% curvature shock, because the standard deviations themselves are in that ratio. Capital requirements driven by these shocks would be dominated by interest-rate level risk, with slope and curvature contributing small but non-trivial increments.</p>
<p>Second, the <strong>Slope scenarios pivot the curve, the Curvature scenarios bow it</strong>. The +k SD steepener (green solid) sits below the baseline at the 2y but above it at the 10y — the curve tilts. The +k SD curvature-up (gold solid) sits above the baseline at the 2y and 10y but below it at the 5y — the curve becomes more bowed. These are not just shifts in level; they are structurally different yield-curve shapes, and a portfolio’s sensitivity to each can differ even at the same notional duration.</p>
<p>Third, the <strong>shocks remain modest in absolute terms</strong> even at 99.5% severity. The widest spread at any tenor is about 18 bps at the 2y between Level-up and Level-down. On a yield curve sitting at 2-3%, this is small relative to historical regime changes. The 99.5% VaR severity at <em>this calibration</em> is closer to “a bad week” than to “a catastrophic year” — a consequence of the small data sample. A real PCA calibrated on years of daily yield changes would produce standard deviations roughly 10-50 times larger than these, and the 99.5% VaR shocks would be correspondingly larger.</p>
<p>A reader extending this to a real capital calculation should be aware of three places this example is too simple. Real curve datasets have fatter tails than Gaussian, so the 2.576 multiplier under-states severity at the 99.5% level; practitioners often use empirical historical quantiles or copulas to capture this. Real datasets also have many more than three tenors, so the principal-component structure is richer (a “second curvature” or fourth factor often appears with 1-2% of variance, as <span class="citation" data-cites="alexander2008market">Alexander (<a href="#ref-alexander2008market" role="doc-biblioref">2008</a>)</span> discusses). And real regulatory regimes have their own prescribed shocks — Solvency II’s interest rate sub-module specifies upward and downward shocks by tenor that are not generally aligned with PCA factor directions. The PCA-based approach above is closer to what an internal-model insurer or bank might use under <span class="citation" data-cites="schlutter2017">Schlütter (<a href="#ref-schlutter2017" role="doc-biblioref">2017</a>)</span> than to a standard formula directly.</p>
</section>
<section id="what-changes-when-going-from-2-tenors-to-many-tenors" class="level2">
<h2 class="anchored" data-anchor-id="what-changes-when-going-from-2-tenors-to-many-tenors">What changes when going from 2 tenors to many tenors</h2>
<p>The mechanism shown here extends without modification to 10 or 60 tenors. What changes:</p>
<ul>
<li>The covariance matrix becomes K × K rather than 3 × 3. The eigendecomposition still produces K eigenvalues and K eigenvectors; the first three almost always carry the L/S/C interpretation; later components capture progressively finer structure (the “fourth factor” is sometimes a second curvature, sometimes a shorter-end tilt; <span class="citation" data-cites="alexander2008market">Alexander (<a href="#ref-alexander2008market" role="doc-biblioref">2008</a>)</span> discusses these).</li>
<li>The variance hierarchy gets more compressed. With many tenors, PC1 typically explains 70–80% rather than 86%, PC2 explains a larger fraction (perhaps 15%), and PC3 captures a smaller share (1–3%). The total captured by the top three components stays in the 90%+ range.</li>
<li>The eigenvector signs of PC2 and PC3 stay recognisable as Slope and Curvature, but the exact loadings depend on the choice of tenor grid. PCA does not know which tenors are “short”, “middle” or “long” — it discovers that the data is organised that way.</li>
<li>Stress testing in practice rarely uses the +1 SD multiplier shown here. The choice of multiplier is a regulatory and modelling decision, not a property of PCA. <span class="citation" data-cites="hull2018risk">Hull (<a href="#ref-hull2018risk" role="doc-biblioref">2018</a>)</span> has worked examples of the conversion between PCA scores and N-standard-deviation stress scenarios for VaR calculations.</li>
</ul>
<p>The earlier <a href="../01-2tenor-toy/index.qmd">Article 1</a> showed the mechanism in a setting where every number was hand-verifiable. This article shows the same mechanism in the smallest setting where the L/S/C interpretation actually appears. For PCA on real yield curve data — many tenors, years of observations, attention to the cross-sectional smoothing required to get sensible eigenvectors — see <a href="../../ics-dns-twd-yc/03-pca-twd/index.qmd">Article 3 of the DNS series</a> (forthcoming), which applies the same machinery to Taiwan TWD yield curves and compares the empirical loadings to Nelson-Siegel basis functions. The series references — <span class="citation" data-cites="litterman1991">Litterman and Scheinkman (<a href="#ref-litterman1991" role="doc-biblioref">1991</a>)</span>, <span class="citation" data-cites="hull2018risk">Hull (<a href="#ref-hull2018risk" role="doc-biblioref">2018</a>)</span>, <span class="citation" data-cites="tuckman2022fixed">Tuckman and Serrat (<a href="#ref-tuckman2022fixed" role="doc-biblioref">2022</a>)</span>, <span class="citation" data-cites="alexander2008market">Alexander (<a href="#ref-alexander2008market" role="doc-biblioref">2008</a>)</span> — are consolidated in <a href="../00-intro/index.qmd">Article 0</a>.</p>
<hr>
<p><em>Source code for the figures in this article is available <a href="https://github.com/kelvin1189/actuarial-modeling-notes/tree/main/posts/pca-yield-curves/02-3tenor/code">in the repo</a>.</em></p>
<p>Comments and corrections welcome.</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-alexander2008market" class="csl-entry" role="listitem">
Alexander, Carol. 2008. <em>Market Risk Analysis, Volume II: Practical Financial Econometrics</em>. Wiley.
</div>
<div id="ref-hull2018risk" class="csl-entry" role="listitem">
Hull, John C. 2018. <em>Risk Management and Financial Institutions</em>. 5th ed. Wiley.
</div>
<div id="ref-litterman1991" class="csl-entry" role="listitem">
Litterman, Robert, and Jose Scheinkman. 1991. <span>“Common Factors Affecting Bond Returns.”</span> <em>Journal of Fixed Income</em> 1 (1): 54–61. <a href="https://doi.org/10.3905/jfi.1991.692347">https://doi.org/10.3905/jfi.1991.692347</a>.
</div>
<div id="ref-schlutter2017" class="csl-entry" role="listitem">
Schlütter, Sebastian. 2017. <span>“Scenario-Based Capital Requirements for the Interest Rate Risk of Insurance Companies.”</span> <em>European Actuarial Journal</em>.
</div>
<div id="ref-tuckman2022fixed" class="csl-entry" role="listitem">
Tuckman, Bruce, and Angel Serrat. 2022. <em>Fixed Income Securities: Tools for Today’s Markets</em>. 4th ed. Wiley.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/kelvin1189\.github\.io\/actuarial-modeling-notes\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<script src="https://utteranc.es/client.js" repo="kelvin1189/actuarial-modeling-notes" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><em>Disclaimer.</em> The content on this website is for educational and informational purposes only and does not constitute financial, investment, legal, or professional actuarial advice. The views expressed here are my own and do not reflect the position of any current or past employer. All code and models are provided “as is” without warranty.</p>
<p><span class="footer-meta">© 2026 Kelvin Wong · Source on <a href="https://github.com/kelvin1189/actuarial-modeling-notes">GitHub</a> · Built with <a href="https://quarto.org">Quarto</a></span></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>